on:
  workflow_call:
    inputs:
      image_name:
        required: false
        type: string
      tag:
        required: false
        type: string

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo secrets
        run: |
          echo "MY_SECRET1=${{ secrets.MY_SECRET }}"
