name: GitHub Actions Demo
run-name: ${{ github.actor }} is building ${{ github.ref }}
on:
  push:
    branches:
      - main

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
    - name: Hello fromJson()
      env:
        fromJ1: ${{ fromJson([hello,from,json]) }}
        fromJ2: ${{ fromJson(hello from json) }}
        fromJ3: ${{ fromJson("{\"hello\": \"from json\"}") }}
      run: |
        echo "$GITHUB_CONTEXT"
