name: GitHub Actions Demo
run-name: ${{ github.actor }} is building ${{ github.ref }}
on:
  push:
    paths:
      - '.github/workflows/**' # Trigger on any changes within the folder
      - 'file.js' # Trigger on changes to this specific file
jobs:

  Dump:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
