on:
  push:
    paths:
      - '.github/workflows/**' # Trigger on any changes within the folder
      - 'file.js' # Trigger on changes to this specific file

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          
